### ISSUE TITLE
toString should be cached

### ISSUE THREAD

**Issue by mericsson** [mixmaxhq/search-string#11]
Let's store the `toString`'ed value and a `dirty` bit to know if we can just re-use it.

**Comment by wearhere** [comment]
Is `toString` called in a tight loop / is it expensive to calculate?

**Comment by wearhere** [comment]
(note that the caching could be done by the client too depending on whether one particular client calls it in a tight loop)

**Comment by mericsson** [comment]
https://github.com/mixmaxhq/search-string/blob/master/src/searchString.js#L277

It's not terrible... but I think it's a cheap enough optimization to give more convenience.
